services:
  backend:
    build: ./be15_DevEagles_BE
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-public
      - app-private

  frontend:
    build: ./be15_DevEagles_FE
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - app-public

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-private

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - app-private

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-private

  tester:
    image: alpine
    container_name: net-tester
    command: sleep 3600       # 실습용으로 쉘 접근 전용
    networks:
      - app-public


networks:
  app-public:
    driver: bridge
  app-private:
    driver: bridge
    internal: true
