apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
    - name: mariadb
      image: mariadb:10.6     # 또는 원하는 버전 (예: 10.11, 11.3 등)
      env:
        - name: MARIADB_ROOT_PASSWORD
          value: "goody"
        - name: MARIADB_DATABASE
          value: "goody"
        - name: MARIADB_USER
          value: "goody"
        - name: MARIADB_PASSWORD
          value: "goody"
      volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mariadb
  volumes:
    - name: mariadb-storage
      persistentVolumeClaim:
        claimName: pvc-mariadb
