apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deveagles

resources:
  - namespace.yml
  - redis.yml
  - zookeeper.yml
  - kafka.yml
  - elasticsearch.yml
  - logstash.yml
  - kibana.yml
  - prometheus.yml
  - grafana.yml
  - boot-deployment.yml
  - vue-deployment.yml
  - ingress.yml

labels:
  - includeSelectors: true
    pairs:
      project: deveagles
      environment: production
